[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
otter = "gLAM4vk4BJnExLP1gw9TDhgzFAgd8cJaQL7EGjimTdm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yogendrarana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
